In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("placement.csv")

In [3]:
df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cgpa     200 non-null    float64
 1   package  200 non-null    float64
dtypes: float64(2)
memory usage: 3.3 KB

In [5]:
y=df["package"]

In [6]:
x=df.drop("package",axis=1)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [10]:
x_train

     cgpa
79   7.18
197  7.21
38   8.62
24   6.53
122  5.12
..    ...
106  6.13
14   7.73
92   7.90
179  7.14
102  5.13

[160 rows x 1 columns]

In [11]:
y_train

79     3.00
197    3.24
38     4.36
24     2.71
122    2.01
       ...
106    2.19
14     3.42
92     4.00
179    3.03
102    1.37
Name: package, Length: 160, dtype: float64

In [12]:
x_test

     cgpa
95   6.63
15   7.25
30   7.36
158  5.95
128  7.93
115  8.35
69   7.30
170  6.22
174  7.32
45   7.87
66   5.11
182  5.88
165  8.21
78   6.59
186  7.84
177  7.09
56   5.84
152  7.37
82   5.58
68   7.56
124  6.06
16   6.84
148  7.57
93   6.79
65   7.60
60   5.61
84   4.26
67   6.51
125  7.33
132  5.84
9    8.31
18   6.94
55   8.20
75   6.97
150  6.30
104  7.62
135  6.10
137  7.14
164  9.06
76   6.94

In [13]:
y_test

95     2.79
15     3.23
30     3.26
158    3.04
128    3.34
115    4.21
69     2.94
170    2.87
174    2.99
45     3.58
66     1.63
182    2.08
165    4.08
78     2.21
186    3.47
177    3.64
56     2.74
152    3.08
82     2.17
68     2.99
124    2.31
16     2.35
148    3.40
93     3.08
65     3.81
60     2.19
84     1.53
67     2.89
125    3.16
132    2.48
9      3.51
18     2.98
55     3.39
75     3.28
150    2.73
104    3.74
135    2.60
137    3.13
164    3.82
76     3.15
Name: package, dtype: float64

In [14]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
model=lr.fit(x_train,y_train)

In [16]:
model.coef_

array([0.57425647])

In [17]:
model.intercept_

np.float64(-1.0270069374542108)