In [94]:
import pandas as pd
import numpy as np
Sales_data=pd.DataFrame({'name':['a',np.nan,np.nan,'d','e'],
                        'region':['ma',np.nan,'mp','gu',np.nan],
                        'sales':[10,np.nan,30,np.nan,50],
                        'expense':[50,np.nan,70,np.nan,90]})
Sales_data

  name region  sales  expense
0    a     ma   10.0     50.0
1  NaN    NaN    NaN      NaN
2  NaN     mp   30.0     70.0
3    d     gu    NaN      NaN
4    e    NaN   50.0     90.0

In [3]:
print(type(np.nan))

<class 'float'>

In [4]:
Sales_data.isna()

    name  region  sales  expense
0  False   False  False    False
1   True    True   True     True
2   True   False  False    False
3  False   False   True     True
4  False    True  False    False

In [5]:
Sales_data.isnull()

    name  region  sales  expense
0  False   False  False    False
1   True    True   True     True
2   True   False  False    False
3  False   False   True     True
4  False    True  False    False

In [8]:
Sales_data.isna().sum()

name       2
region     2
sales      2
expense    2
dtype: int64

In [9]:
Sales_data.dropna()

  name region  sales  expense
0    a     ma   10.0     50.0

In [18]:
Sales_data.dropna(inplace=True)

In [16]:
Sales_data

  name region  sales  expense
0    a     ma   10.0     50.0

In [28]:
Sales_data.dropna(how="any")

  name region  sales  expense
0    a     ma   10.0     50.0

In [38]:
Sales_data.dropna(thresh=3) # AT least 3 or more than Three Non-Null Values Required or else it will be Removed.

  name region  sales  expense
0    a     ma   10.0     50.0
2  NaN     mp   30.0     70.0
4    e    NaN   50.0     90.0

In [56]:
Sales_data.dropna(axis=0)

  name region  sales  expense
0    a     ma   10.0     50.0

In [49]:
Sales_data.dropna(subset=["sales","expense"])

  name region  sales  expense
0    a     ma   10.0     50.0
2  NaN     mp   30.0     70.0
4    e    NaN   50.0     90.0

In [29]:
help(Sales_data.dropna)

Help on method dropna in module pandas.core.frame:

dropna(*, axis: 'Axis' = 0, how: 'AnyAll | lib.NoDefault' = <no_default>, thresh: 'int | lib.NoDefault' = <no_default>, subset: 'IndexLabel | None' = None, inplace: 'bool' = False, ignore_index: 'bool' = False) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or sequence of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
    ...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    ...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
    ...                             pd.NaT]})
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis='columns')
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how='all')
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=['name', 'toy'])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

In [57]:
Sales_data.fillna(0)

  name region  sales  expense
0    a     ma   10.0     50.0
1    0      0    0.0      0.0
2    0     mp   30.0     70.0
3    d     gu    0.0      0.0
4    e      0   50.0     90.0

In [58]:
Sales_data['sales'].fillna(Sales_data["sales"].mean())

0    10.0
1    30.0
2    30.0
3    30.0
4    50.0
Name: sales, dtype: float64

In [59]:
Sales_data['sales'].fillna(Sales_data["sales"].median())

0    10.0
1    30.0
2    30.0
3    30.0
4    50.0
Name: sales, dtype: float64

In [73]:
Sales_data['sales'].fillna(Sales_data["sales"].mode())

0    10.0
1    30.0
2    30.0
3     NaN
4    50.0
Name: sales, dtype: float64

In [83]:
Sales_data.drop("name",axis=1)

  region  sales  expense
0     ma   10.0     50.0
1    NaN    NaN      NaN
2     mp   30.0     70.0
3     gu    NaN      NaN
4    NaN   50.0     90.0

In [80]:
help(Sales_data.drop)

Help on method drop in module pandas.core.frame:

drop(labels: 'IndexLabel | None' = None, *, axis: 'Axis' = 0, index: 'IndexLabel | None' = None, columns: 'IndexLabel | None' = None, level: 'Level | None' = None, inplace: 'bool' = False, errors: 'IgnoreRaise' = 'raise') -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['llama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=('falcon', 'weight'))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

In [97]:
Sales_data.drop(Sales_data.index)

Empty DataFrame
Columns: [name, region, sales, expense]
Index: []

In [98]:
df=pd.DataFrame({"maths":[80,85,90],
                "science":[78,82,88],
                "English":[70,75,80]})
df

   maths  science  English
0     80       78       70
1     85       82       75
2     90       88       80

In [99]:
help(df.apply)

Help on method apply in module pandas.core.frame:

apply(func: 'AggFuncType', axis: 'Axis' = 0, raw: 'bool' = False, result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None, args=(), by_row: "Literal[False, 'compat']" = 'compat', engine: "Literal['python', 'numba']" = 'python', engine_kwargs: 'dict[str, bool] | None' = None, **kwargs) method of pandas.core.frame.DataFrame instance
    Apply a function along an axis of the DataFrame.

    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument.

    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:

        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.

    raw : bool, default False
        Determines if row or column is passed as a Series or ndarray object:

        * ``False`` : passes each row or column as a Series to the
          function.
        * ``True`` : the passed function will receive ndarray objects
          instead.
          If you are just applying a NumPy reduction function this will
          achieve much better performance.

    result_type : {'expand', 'reduce', 'broadcast', None}, default None
        These only act when ``axis=1`` (columns):

        * 'expand' : list-like results will be turned into columns.
        * 'reduce' : returns a Series if possible rather than expanding
          list-like results. This is the opposite of 'expand'.
        * 'broadcast' : results will be broadcast to the original shape
          of the DataFrame, the original index and columns will be
          retained.

        The default behaviour (None) depends on the return value of the
        applied function: list-like results will be returned as a Series
        of those. However if the apply function returns a Series these
        are expanded to columns.
    args : tuple
        Positional arguments to pass to `func` in addition to the
        array/series.
    by_row : False or "compat", default "compat"
        Only has an effect when ``func`` is a listlike or dictlike of funcs
        and the func isn't a string.
        If "compat", will if possible first translate the func into pandas
        methods (e.g. ``Series().apply(np.sum)`` will be translated to
        ``Series().sum()``). If that doesn't work, will try call to apply again with
        ``by_row=True`` and if that fails, will call apply again with
        ``by_row=False`` (backward compatible).
        If False, the funcs will be passed the whole Series at once.

        .. versionadded:: 2.1.0

    engine : {'python', 'numba'}, default 'python'
        Choose between the python (default) engine or the numba engine in apply.

        The numba engine will attempt to JIT compile the passed function,
        which may result in speedups for large DataFrames.
        It also supports the following engine_kwargs :

        - nopython (compile the function in nopython mode)
        - nogil (release the GIL inside the JIT compiled function)
        - parallel (try to apply the function in parallel over the DataFrame)

          Note: Due to limitations within numba/how pandas interfaces with numba,
          you should only use this if raw=True

        Note: The numba compiler only supports a subset of
        valid Python/numpy operations.

        Please read more about the `supported python features
        <https://numba.pydata.org/numba-doc/dev/reference/pysupported.html>`_
        and `supported numpy features
        <https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html>`_
        in numba to learn what you can or cannot use in the passed function.

        .. versionadded:: 2.2.0

    engine_kwargs : dict
        Pass keyword arguments to the engine.
        This is currently only used by the numba engine,
        see the documentation for the engine argument for more information.
    **kwargs
        Additional keyword arguments to pass as keywords arguments to
        `func`.

    Returns
    -------
    Series or DataFrame
        Result of applying ``func`` along the given axis of the
        DataFrame.

    See Also
    --------
    DataFrame.map: For elementwise operations.
    DataFrame.aggregate: Only perform aggregating type operations.
    DataFrame.transform: Only perform transforming type operations.

    Notes
    -----
    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    Examples
    --------
    >>> df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
    >>> df
       A  B
    0  4  9
    1  4  9
    2  4  9

    Using a numpy universal function (in this case the same as
    ``np.sqrt(df)``):

    >>> df.apply(np.sqrt)
         A    B
    0  2.0  3.0
    1  2.0  3.0
    2  2.0  3.0

    Using a reducing function on either axis

    >>> df.apply(np.sum, axis=0)
    A    12
    B    27
    dtype: int64

    >>> df.apply(np.sum, axis=1)
    0    13
    1    13
    2    13
    dtype: int64

    Returning a list-like will result in a Series

    >>> df.apply(lambda x: [1, 2], axis=1)
    0    [1, 2]
    1    [1, 2]
    2    [1, 2]
    dtype: object

    Passing ``result_type='expand'`` will expand list-like results
    to columns of a Dataframe

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='expand')
       0  1
    0  1  2
    1  1  2
    2  1  2

    Returning a Series inside the function is similar to passing
    ``result_type='expand'``. The resulting column names
    will be the Series index.

    >>> df.apply(lambda x: pd.Series([1, 2], index=['foo', 'bar']), axis=1)
       foo  bar
    0    1    2
    1    1    2
    2    1    2

    Passing ``result_type='broadcast'`` will ensure the same shape
    result, whether list-like or scalar is returned by the function,
    and broadcast it along the axis. The resulting column names will
    be the originals.

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='broadcast')
       A  B
    0  1  2
    1  1  2
    2  1  2

In [106]:
print(df.apply(sum))

maths      255
science    248
English    225
dtype: int64

In [102]:
result=df.apply(lambda x:x.mean())
print(result)

maths      85.000000
science    82.666667
English    75.000000
dtype: float64

In [111]:
result=df.apply(lambda x:x.mean(),axis=1,raw=True)
print(result)

0    76.000000
1    80.666667
2    86.000000
dtype: float64

In [112]:
result=df.apply(lambda x:[x.sum(),x.mean()],axis=1,result_type='expand')
print(result)

       0          1
0  228.0  76.000000
1  242.0  80.666667
2  258.0  86.000000

In [113]:
result=df.apply(lambda x:[x.sum(),x.mean()],axis=1)
print(result)

0                 [228, 76.0]
1    [242, 80.66666666666667]
2                 [258, 86.0]
dtype: object

In [115]:
result=df.apply(lambda x:x-x.mean(),axis=1,result_type="broadcast")
print(result)

   maths  science  English
0      4        2       -6
1      4        1       -5
2      4        2       -6

In [117]:
def add_bonus(x,bonus ):
    return x+bonus
result=df.apply(add_bonus,args=[5])
print(result)

   maths  science  English
0     85       83       75
1     90       87       80
2     95       93       85

In [119]:
def add_bonus(x,bonus1,bonus2):
    return x+bonus1+bonus2
result=df.apply(add_bonus,args=[5,10])
print(result)

   maths  science  English
0     95       93       85
1    100       97       90
2    105      103       95

In [120]:
df["maths"]=df["maths"].astype(float)
df

   maths  science  English
0   80.0       78       70
1   85.0       82       75
2   90.0       88       80